spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shop_db
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



file:
  upload-dir: E:\Java\SpringBoot\food_project_fe\preview\osahan-eat\theme-sidebar\img

