spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shop_db
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: vinhvinh250@gmail.com
    password: ueilvsebbbevksrj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




file:
  upload-dir: /img


server:
  servlet:
    context-path: /api


